### ISSUE TITLE
New menu bugs

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1184]
There are several bugs on the menu as is on the dev server.

- [x] Back button isn't working always, once on a project specification page, the back button stops working; #1189 
- [x] Back button hover style isn't working 100% - needs to be fixed to trigger the arrow switch as soon as the pointer hovers over the circle or the text label (arrow should be handled as part of the circle) #1190 
- [x] Cards on secondary category page aren't displaying icons to spec - they are scaled down versions of the main cards, in design they are not - follow the design prototype from Didi as a guide.
- [x] Menu titles + subtitles are not to spec -> follow from here https://invis.io/U3DJPB4DR#/254024918_main_Project_Menu
- [x] Button text on category cards should read "View all" (hover on Design in the InVision prototype) #1191

**Comment by vikasrohit** [comment]
@vic-topcoder It is difficult to manage these as list items. It would be better manageable if they are different issues in github because I used to commit against each github issue which lets us revert a particular issue in case of any troubles with that fix. I have created separate issues and updated the issue description with those issues.

>Menu titles + subtitles are not to spec -> follow from here https://invis.io/U3DJPB4DR#/254024918_main_Project_Menu

Can you please let me know what specifically is not as per design?  I have copied exact styles from Didi's prototype. 
**Didi's Prototype**
<img width="1276" alt="screen shot 2017-09-22 at 12 29 00 pm" src="https://user-images.githubusercontent.com/2417632/30732919-53097a36-9f92-11e7-8292-411018663855.png">
**From dev**
<img width="1280" alt="screen shot 2017-09-22 at 12 30 19 pm" src="https://user-images.githubusercontent.com/2417632/30732931-624a1870-9f92-11e7-8544-b47e304567d1.png">
**Didi's Prototype**
<img width="1277" alt="screen shot 2017-09-22 at 12 29 28 pm" src="https://user-images.githubusercontent.com/2417632/30732924-5742aa50-9f92-11e7-8423-49baadee7766.png">
**From dev**
<img width="1280" alt="screen shot 2017-09-22 at 12 30 08 pm" src="https://user-images.githubusercontent.com/2417632/30732927-5e1e49b0-9f92-11e7-8b9d-9ab7a1ed98ff.png">

**Comment by vic-topcoder** [comment]
@vikasrohit please feel free to create a new issue for each of the issues. It would take me too much time to organize GitHub and manage it the way Filipp did.

**Comment by vic-topcoder** [comment]
Re: style seems ok to me currently

**Comment by vikasrohit** [comment]
@vic-topcoder We can always track in terms of milestones for an abstract view, however, from the development perspective it is easy to have separate issue for different portions of the application because we may want to cherry pick or revert particular change done by an issue. Yes, in case the changes are very trivial, we can keep them under same issue as check list.

**Comment by vikasrohit** [comment]
Closing
