### ISSUE TITLE
[$250] Milestone and phase dates

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#2245]
- [x] When creating new phase, start date should be set as last phase end date +1 day, or current date if there are no phases
- [x] remove the options to set start/end date for a milestone, only duration can be set (update the UI and the api call)
- [x] if a phase has a timeline, disable changing the end date and add a tooltip over the end date saying `Phase end date is controlled by duration of individual milestones`

![image](https://user-images.githubusercontent.com/3051646/43366701-5984f594-9342-11e8-9621-0b61838964b2.png)

![image](https://user-images.githubusercontent.com/3051646/43366723-8e4654b2-9342-11e8-9c9b-e6c70159a013.png)

**Comment by gondzo** [comment]
@Gauravseta can you take this one?

**Comment by Gauravseta** [comment]
@gondzo sure

**Comment by RishiRajSahu** [comment]
@Gauravseta @gondzo added one more item to the list.

**Comment by vikasrohit** [comment]
@Gauravseta @gondzo @RishiRajSahu I think we don't need the second item in the list. Rather we need to hide option of updating phase duration when there is a timeline associated with a phase and show the duration field only when there is no timeline received for the phase's product. This is to be backward compatible with project/phases which were created without timeline.

And better, instead of hiding the duration field (when there is a timeline), disable that field and show a tooltip saying that `Phase's duration is controlled by its milestones, please update specific milestone's duration instead`.

fyi @rmjmccormick @acshields @vic-topcoder its as per our discussion in last call.

**Comment by Gauravseta** [comment]
@gondzo i hope its given to me as m working on it.

**Comment by vikasrohit** [comment]
@gondzo Did quite understand it. Agree, that it throws error when we try to set milestone's start/end dates out of bound of timeline's (effectively phase's) start/end dates, but where do we need to set it out of bounds?

I think the last item in the list is already handled now in backend via https://github.com/topcoder-platform/tc-project-service/issues/126. Is this what you are looking for @gondzo?

**Comment by gondzo** [comment]
@Gauravseta yes, it's still assigned to you

**Comment by gondzo** [comment]
@vikasrohit see the bellow screenshot. Manager wants to set first milestone dates outside of bounds of the phase. If we disable updating phase dates, then the api has to allow for such change

![image](https://user-images.githubusercontent.com/3051646/43365485-f02dd1f6-932d-11e8-921d-4a87ff495ea0.png)


> I think the last item in the list is already handled now in backend via topcoder-platform/tc-project-service#126. Is this what you are looking for @gondzo?

That's the case when timeline dates are updated, but we're talking about phase dates.

IMO we have too many dates:
phase start/end
timeline start/end
each milestone start/end

do we actually need both phase and timeline dates? those should always be the same, it's 1-1 relation.
also, phase start/end should be updated by the api when a milestone is updated

**Comment by vikasrohit** [comment]
> do we actually need both phase and timeline dates? those should always be the same, it's 1-1 relation.

That is correct. But as we are gradually moving from project plan without timeline to project plan with timeline, we have multiple dates. What we are trying to do here is to abstract the timeline details behind phase dates. I mean when user is setting the phase's start/end date, we should update the timeline's dates as well.

>also, phase start/end should be updated by the api when a milestone is updated

Yes. But I don't want to make milestone to be coupled with phase/product. So, we have two options:
1. Update the phase's dates by listening to the bus event of milestone update OR
2. Just don't read end date of phase when it has timeline/milestone associated. Only read `startDate` of the phase which essentially maps 1:1 to timeline's `startDate`.

I agree we need to remove the validation on milestone update. Creating issue for it.

**Comment by gondzo** [comment]
@Gauravseta we need to change the requirements for the second and third task. I'll update the prize here for these changes. 
I've updated the first post with the new requirements. The changes are:
- remove the options to set start/end date for a milestone, only duration can be set (update the UI and the api call)
- if a phase has a timeline, disable changing the end date and add a tooltip over the end date saying `Phase end date is controlled by duration of individual milestones`

![image](https://user-images.githubusercontent.com/3051646/43366701-5984f594-9342-11e8-9621-0b61838964b2.png)

![image](https://user-images.githubusercontent.com/3051646/43366723-8e4654b2-9342-11e8-9c9b-e6c70159a013.png)

**Comment by gondzo** [comment]
@Gauravseta let me know if you're still ok with working on this task

**Comment by Gauravseta** [comment]
@gondzo yes m ok working on it and have already started.

**Comment by vikasrohit** [comment]
@Gauravseta Can we simply set startDate of the new phase, being added, as `endDate + 1` of the last phase (by ascending order of startDate). Our backend should already be returning the phases in the desired order.

**Comment by Gauravseta** [comment]
@vikasrohit please keep this in bug bash .i will complete it within 2 hrs.its near to done.

**Comment by Gauravseta** [comment]
@gondzo @vikasrohit unable to load milestones in project plan tab. console says "Cannot read property 'milestones' of undefined". Its after taking latest code. is it any backend error?

**Comment by gondzo** [comment]
any specific project. they load fine for me at http://local.topcoder-dev.com:3000/projects/6746/plan

**Comment by Gauravseta** [comment]
@gondzo  above url working well

can you please check this : http://localhost:3000/projects/6583/plan.

thanks

**Comment by gondzo** [comment]
@Gauravseta it's a data issue, there are no timelines under that phase, just use a new project

**Comment by gondzo** [comment]
@Gauravseta let me know if there is anything not clear about the remaining two tasks, we need to close this one asap

**Comment by Gauravseta** [comment]
@gondzo near to complete second task and third task is minor. till now all is clear in my mind and working on number field for second task.

**Comment by Gauravseta** [comment]
@gondzo task 2 completed. screenshot of it.
![milestoneedit](https://user-images.githubusercontent.com/16337895/43414288-f998d132-944f-11e8-9c9f-0358a4df08c1.png)

**Comment by Gauravseta** [comment]
@gondzo i noticed just now.
task 3 is contradictiing
1. in description, it is to disable the enddate but in picture it shows disable duration, whereas description says add tooltip "Phase end date is controlled by duration of individual milestones".

2. so i guess you meant to say that "Phase duration is controlled by duration of individual milestones ".

I am implementing like that assuming u meant "duration" and not "end date"

**Comment by gondzo** [comment]
you're right, it should be phase duration

**Comment by Gauravseta** [comment]
@gondzo raising PR within 5mins for this issue with all 3 tasks done.

**Comment by Gauravseta** [comment]
@gondzo tooltip in black background okay?

**Comment by gondzo** [comment]
just use the default tooltip styling, ex https://github.com/appirio-tech/connect-app/blob/ad9d85e2252aa3d32203b128107fd274cd88fe44/src/components/FileList/FileListItem.jsx#L106

**Comment by Gauravseta** [comment]
@gondzo tooltip screenshot
![phasetooltip](https://user-images.githubusercontent.com/16337895/43418281-075e2140-945b-11e8-85db-f7ff53e37de3.png)

**Comment by gondzo** [comment]
Thanks. Tooltip looks great. Can you take a look at field alignment, first, second and third row don't look ok in the screenshot

**Comment by Gauravseta** [comment]
@gondzo genuinelly speaking having low end laptop its really lagging to open inspect tools of google chrome. whatever alignment misplaced due to disabling has been resolved. also tried best to align it than how it was. i hope you will consider it as not complete dealignment was due to me , to the best of my knowledge. thanks

**Comment by Gauravseta** [comment]
@gondzo i can say its at much better stage than before. PR has been updated.

**Comment by RishiRajSahu** [comment]
@Gauravseta could you verify the first point once again on your side ? i added website development as a new phase but the timeline is not honouring the startDate logic.

![screen shot 2018-07-31 at 12 05 18 pm](https://user-images.githubusercontent.com/11248478/43441987-35095ef2-94ba-11e8-9d7d-d0b86d2aba9b.png)

**Comment by Gauravseta** [comment]
@RishiRajSahu i will look into it immediatslly.
But i feel surely there is an mismatch in data when responsr recieved.
because while sending request for new phase. what i do is :
i sort phases in ascending order of startdate, then i pick phase which is last in sorted order, then i take endDate of that last phase ,and make it as startDate of new phase and add 17 days for endDate of new phase.
So u can see 10th August is startdate and 27 august is enddate of new phase ,hence request is sent perfectly to backend and phase is made ,but when data is received ,phase contains timeline which is mismatched and was never sent me by  me. hence i feel on backend some date mismatch while creating timeline milestones as it was not set by me or even sent by me.

you can observe already the phase present had enddate of August 9 , and new phase has startdate of august 10 , thats how my logic works as explained to u above.

correct me if m wrong

**Comment by RishiRajSahu** [comment]
@Gauravseta along with phase `startDate`, timeline's `startDate` should also updated i.e. phase `startDate` and timeline `startDate` should be same. 
You can check this method `createTimelineAndMilestoneForProduct` to update the timelines `startDate` to be set as phase `startDate`. Also you can avoid setting `endDate` for the timeline in this method even the call for milestone templates `getMilestoneTemplates` could be removed  because we don't want to derive timeline's `startDate` and `endDate` from milestone's date anymore.

**Comment by Gauravseta** [comment]
@RishiRajSahu i will look into it immediately and update u on the same but kindly consider it for closing as task requirements are already met and i do wish that it gets completed in this bug bash itself.

**Comment by RishiRajSahu** [comment]
@Gauravseta Thanks! yeah update me once the PR has these changes, I will close the task, this was the final piece missing.

**Comment by Gauravseta** [comment]
@RishiRajSahu as u said all has been met in latest update.I hope this issue will be closed and paid out before bug bash ends as all requirements are met of this ticket. thanks

**Comment by vikasrohit** [comment]
@Gauravseta we are still evaluating. We have to evaluate that the changes are not causing any regressions along with meeting the current requirements.
Be assured, we will close bug and payments would be processed as per process.

**Comment by RishiRajSahu** [comment]
@Gauravseta could you check this line of code https://github.com/appirio-tech/connect-app/blob/feature/timeline-milestone/src/projects/actions/project.js#L240 ,I can add the phase successfully to existing projects but I am not able to create a new project ?

Review phase is still ON.

**Comment by RishiRajSahu** [comment]
Fixed with https://github.com/appirio-tech/connect-app/commit/37e4ab46ba8f01ae1c9335de68c71b93e2db355a, evaluating other changes, will close ASAP.

**Comment by Gauravseta** [comment]
@RishiRajSahu thanks.

**Comment by Gauravseta** [comment]
@gondzo payments are  not reflected yet in my profile whereas it has been marked PAID. can you please check?

**Comment by Gauravseta** [comment]
@gondzo sorry .its being reflected now. thanks
