### ISSUE TITLE
Timeline additional issues

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2301]
Ok, here are several issues that I'm going to capture in a list. @acshields @vikasrohit @RishiRajSahu please break them between releases and importance.

Current implementation
![screen shot 2018-08-06 at 10 08 04 am](https://user-images.githubusercontent.com/8484061/43744247-02d25d66-998e-11e8-89e7-b35d8e7e996a.png)

Designed
![screen shot 2018-08-06 at 10 08 12 am](https://user-images.githubusercontent.com/8484061/43744248-071eb0d6-998e-11e8-9cce-38a12de84be0.png)

The goal of this is to ensure the customer has selected all the checkpoint winners to continue to the final stage.

![screen shot 2018-08-06 at 3 41 16 pm](https://user-images.githubusercontent.com/8484061/43744503-2d6ad1ba-998f-11e8-8ac5-a144181d8772.png)

Expected
![screen shot 2018-08-06 at 3 42 32 pm](https://user-images.githubusercontent.com/8484061/43744546-5da6580e-998f-11e8-8619-07463f20455c.png)

What would be a better content to explain next steps in the project and get customers moving? Research with Sales.

Starts as "Add link"
![screen shot 2018-08-06 at 4 36 50 pm](https://user-images.githubusercontent.com/8484061/43746117-21dd7d72-9997-11e8-8150-3fa22859565f.png)
and switches to "Add a link".
![screen shot 2018-08-06 at 4 36 56 pm](https://user-images.githubusercontent.com/8484061/43746128-2fce55e6-9997-11e8-8a10-c712868e54f8.png)

Please use consistent labeling in both cases (@acshields please advise on language). You're adding 1 link at a time (thus I would say "add a download link" to initiate the process, and "Add link" in the expanded state to drive the interaction.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] Remove specification milestone duration (timeline starts). When we have a timeline start most of the time we don't want to set a timeline for the customer to complete a specification. The goal is to flip the switch once the specification is ready and the copilot can start the challenges on the platform. We already made the specification document optional, so let's remove further constraints from the system and make sure that the first checkpoint is the agreement on specification, which would record the start of work and transition into the next milestone in the timeline. #2412 

- [x] Remove delivery milestone duration (timeline ends). Once the work is done we do a deliver as a single point in time, and the customer has no further option to extend/expand request for fixes. The delivery literally marks the end of the phase and provides a link (or links) to the customer to download their artifacts/deliverables. #2413 

- [x] Design checkpoint button should be enabled only if you have:
  - less than 5 designs to select
  - selected 5 designs out of a 6+ options available. #2410 

- [x] Review state of the milestone is really separate thing. Each review has 2 days to be completed. For the sake of simplicity we combined the work and the review into a single milestone. Once we complete the work, the review time starts. Right now this is not clear from the button label. (check the screenshot above). #2414 

- [x] Remove messages for adding a phase to a project plan. This is done by managers and makes no sense as I can see what I've just added. The customer can't see a phase when it is in draft state (as added) and it makes no sense to dispatch this message.
![screen shot 2018-08-06 at 2 51 25 pm](https://user-images.githubusercontent.com/8484061/43744296-44883d98-998e-11e8-8895-9bc5e7bb623b.png) #2415 

- [x] Remove the "submit for review" button as our project scope has the exact same data from project creation. This makes no sense at the moment. We're going towards a state where all the project scope data would be submitted at one step and once project is completed it would be ready for review (generate project plan) #2417 

- [x] Hide $0 as cost/estimate from the customer. Our customers should only see data that is relevant. #2418 

- [x] Do not display project status bar twice on the Project Scope tab. This makes no sense (Hide one of the two progress bars). @acshields I'm leaving you to pick which one of the progress bars should stay. I would probably hide the big progress bar as the jump from the sidebar to the main space would be too much). #2419 

- [x] Hide project status from customer. We build the new progress bar at the moment and it would be sufficient for communication. The project status should be visible for managers and copilots. Also - let's make sure we tackle the logic of switching project status based on the dependent phase status. #2420 

- [x] Rename `Channels` and `Posts` to `Discussions` to keep things consistent.
![screen shot 2018-08-06 at 3 45 06 pm](https://user-images.githubusercontent.com/8484061/43744660-d77037d6-998f-11e8-8c07-15fddd4f5231.png) #2421 

- [x] Make sure the welcome post for a new project actually makes sense. The current scope section doesn't have additional data to submit, and we don't want our customers to reach out to support via email. #2479 
> Coder the Bot2:17 pm
Hello, Coder here! Your project 'App design sample test project' has been created successfully. For your next step, please head over to the Scope section and answer all of the required questions. If you already have a document with your requirements, just verify it against our checklist and then upload it. Once you're done, hit the "Submit for Review" button on the Specification. Get stuck or need help? Email us at support@topcoder.com.

- [x] Implement the visual notification for new items on a phase (red dot). The customer doesn't have a way to spot when there is a new post or change on the timeline on the phase card at the moment, as it is collapsed. #2455 

- [x] Make sure the customer can see the currently active phase card. By design we wanted to expand the currently active card to display the timeline when the customer loads the dashboard and project plan (save a click to the customer). #2478 

- [x] Do not make a welcome post to the phase discussion (Posts tab) before the phase is active. Even then it would be nice to actually have a post from the copilot and a more meaningful message depending on the type of the phase. Right now the message doesn't help the customer to do anything, and is a noise for the manager. #2477 
![screen shot 2018-08-06 at 4 01 26 pm](https://user-images.githubusercontent.com/8484061/43745125-021485bc-9992-11e8-8584-ee8020eaef32.png)

- [x] User avatar in the post composer (footer) is not aligned with the avatar from the actual post. #2480 
![screen shot 2018-08-06 at 4 01 54 pm](https://user-images.githubusercontent.com/8484061/43745161-30fcca60-9992-11e8-952a-27ad2897b70b.png)

- [x] Selected designs should have blue background
![screen shot 2018-08-06 at 10 07 06 am](https://user-images.githubusercontent.com/8484061/43745223-85602d04-9992-11e8-8c43-4aa73c96b3ef.png)

- [x] Extension can't be requested during design review. Please remove the button while we're in review. #2481 

- [x] After editing a milestone properties, the hover state still persists. I have to hover over the milestone to remove the highlight. [NOT REPRODUCIBLE]
![screen shot 2018-08-06 at 4 08 39 pm](https://user-images.githubusercontent.com/8484061/43745344-0ff1290a-9993-11e8-9e09-712dbae22380.png)
![screen shot 2018-08-06 at 4 09 30 pm](https://user-images.githubusercontent.com/8484061/43745354-1e59710a-9993-11e8-8e9f-6dd62794d4cf.png)

- [x] Design links URL should be aligned to the right and 30px from the widest text element `design link name`. Right now the checkpoint and final design links URL are not uniform (they should). #2482 
![screen shot 2018-08-06 at 4 27 49 pm](https://user-images.githubusercontent.com/8484061/43745873-f0cfc790-9995-11e8-8da7-de5c40d2b254.png)

- [x] Post formatting is missing: #2201 
  - Links (should be blue)
  - @mention - (should be bold)
- [x] `@mention` should not lead to the profile page; let's remove the profile link - we don't want customers to go to the community profile page at this time. #2476 
- [x] Final fixes add a new line button looks wierd #2484 
![screen shot 2018-08-06 at 4 35 38 pm](https://user-images.githubusercontent.com/8484061/43746052-d47d0d68-9996-11e8-9506-1700c5e1467a.png)

- [x] When an additional design is selected, removing one of the first 3 placements keeps the selected state (blue) of the previously "additional" element #2490 
![screen shot 2018-08-06 at 4 33 45 pm](https://user-images.githubusercontent.com/8484061/43745991-84593d84-9996-11e8-9d59-79917b379b43.png)
- [x] Links are not editable once the delivery is completed, but they should be. What would happen if a copilot moves things after they've completed adding links, and there's an error? Keep the option to edit/remove links for manager/copilots/admins at all times. @acshields FYI #2492

- [x] When a place was selected (final designs), do not allow more places to be selected within the same design. To reproduce: make sure you have 5 designs, select paces from 1 to 3, select an additional design, remove first place: #2577   ![screen shot 2018-08-06 at 4 30 26 pm](https://user-images.githubusercontent.com/8484061/43745930-291b8346-9996-11e8-878f-b09838e6d1f1.png)

- [x] Checkboxes are not using the standard border (or it seems like it) #2578 
![screen shot 2018-08-06 at 4 04 40 pm](https://user-images.githubusercontent.com/8484061/43745207-7574c5da-9992-11e8-9bc0-e03170d756a4.png)
![screen shot 2018-08-06 at 4 04 40 pm](https://user-images.githubusercontent.com/8484061/43745224-880a04f8-9992-11e8-83f4-d25f0e9b916f.png)
- [x] Adding link for final fixes button text is different in states. #2580 

- [x] Restore Coder the Bot avatar. It's gone missing somehow. #2576 

<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-288

**Comment by RishiRajSahu** [comment]
@vic-topcoder not reproducible
> After editing a milestone properties, the hover state still persists. I have to hover over the milestone to remove the highlight.

**Comment by vic-topcoder** [comment]
@RishiRajSahu - the button text changes during different states. It should stay the same:
"Add link" becomes "Add a link".
![screen shot 2018-10-03 at 12 04 37 pm](https://user-images.githubusercontent.com/8484061/46433020-a3ff1500-c704-11e8-9d3b-032c60b2fd99.png)
![screen shot 2018-10-03 at 12 04 31 pm](https://user-images.githubusercontent.com/8484061/46433021-a3ff1500-c704-11e8-8ff2-d3fa1a3c4ded.png)

**Comment by RishiRajSahu** [comment]
thanks @vic-topcoder

**Comment by RishiRajSahu** [comment]
Closing as all the action items are divided into issues and completed/tracked there.
