### ISSUE TITLE
Final milestone types for 2.4.4

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2333]
We had a review with @acshields. We should have the basic milestone types as follow:

1. **Timeline start** (optional specification link).
2. **Report milestone** (can be extended)
  A. Development (display progress bar to customer, copilot edits details)
  B. Design (display progress bar to customer & add designs links for review)
3. **Review milestone**
  A. Design checkpoint (customer selects 5 designs)
  B. Design final (customer selects 3 designs in order to buy)
  C. RUX final (customer selects 8 designs in order to buy)
4. **Timeline end** (Delivery with optional final fixes)
  A.Final fix
  B. Delivery link

We decided to split the design report and design review as separated milestones going forward, so the customers can better understand how the process is going forward (when am I supposed to complete the review).

We also would like to optimize the milestone messages for customers and managers to better guide both parties during the process. There are certain requirements and reminders we can present to the copilots while a phase is being worked upon. This would make it easier for them to get started and repeatedly manage the requirements.

Bellow is the customer view of an example design iteration with 1 report (final designs), and no final fixes, including the changes we added after today's review:
![design phase with 1 report no fixes](https://user-images.githubusercontent.com/8484061/43878534-8d802bc4-9b54-11e8-8bdd-ad4b93b754e4.png)

We should try to implement these changes for the 2.4.4 release.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] Remove the description message above the timeline. It is not possible to edit those and we will use the "planned" state to explain what will happen in the phase.

- [x] When a milestone is in any state but completed, the date on the left should be colored with $tc-gray-30 to illustrate a planned date state. Once the milestone is completed, the date would be final (day of competition) and should use $tc-black as color. #2446 

- [x] Separate the report and review as stand-alone milestones.
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-317

**Comment by vikasrohit** [comment]
Sorry @vic-topcoder, we missed to implement these final minor requirements in the 2.4.4 release. We can keep them in 2.4.5. We have already implemented all milestones as per our `Milestone Requirements` excel.

**Comment by vikasrohit** [comment]
>  Remove the description message above the timeline. It is not possible to edit those and we will use the "planned" state to explain what will happen in the phase.

@vic-topcoder that is description the phase which we can make editable if you would like, otherwise we can just remove it as you said above.

**Comment by vikasrohit** [comment]
Closing as required changes are done and #2446 is created the minor thing remaining.
