### ISSUE TITLE
[$45] Fix issues on Connect Registration page

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2857]
This issue combines inside several small issues on Connect Registration page, which are easier to fix together.

It includes the next issues:
- [x] Make the link on the right sidebar clickable https://github.com/appirio-tech/connect-app/issues/2572#issuecomment-466993511
- [x] Fix **Continue** button enabling https://github.com/appirio-tech/connect-app/issues/2854
- [x] Remove + requirement for phone numbers https://github.com/appirio-tech/connect-app/issues/2853

The work for this issue has to be done in the repo https://github.com/appirio-tech/react-components/tree/feature/connectv2 branch `feature/connectv2`

For testing Registration Page, https://github.com/appirio-tech/accounts-app can be run locally.

**Comment by akumar1503** [comment]
Please assign this to me. 
Thanks.

**Comment by maxceem** [comment]
@akumar1503 you can start working on it since your comment. To make it clear I've sent you an invitation to the repo, as soon as you accept it I could mark you as assigned.

**Comment by akumar1503** [comment]
@maxceem 
i have an issue with testing the [react-components](https://github.com/appirio-tech/react-components/tree/feature/connectv2) app locally.

I have to test these two components:

- [RegistrationScreen](https://github.com/appirio-tech/react-components/tree/feature/connectv2/components/RegistrationScreen)
- [WizardRight](https://github.com/appirio-tech/react-components/tree/feature/connectv2/components/Wizard/WizardRight)

As you mentioned above, accounts-app should be used(i have cloned dev branch). However it doesn't uses above components. Do i need to work on some other branch?
How can i test these components?

**Comment by maxceem** [comment]
@akumar1503 I think you don't really need to run `react-components` locally.

The next appraoch should work:
- clone `accounts-app` branch `dev` locally
- Ensure that you have an alias for `local.topcoder-dev.com` to `127.0.0.1` in your hosts file
- `npm install`
- `npm run dev` - should run accounts-app locally in dev mode
- open http://local.topcoder-dev.com:3100/connect/registration in your browser, you will see registration form

For details on how to run `accounts-app` locally, see [README](https://github.com/appirio-tech/accounts-app).

Under the hood, it will use files from `react-components` which are installed as a dependency in `node_modules` folder. For example `node_modules/appirio-tech-react-components/components/RegistrationScreen/index.jsx`.

You can update files of `react-components` inside `node_modules` first, and after clone `react-component` repo branch `feature/connectv2` in some other folder and copy updated files from `node_modules` to the repo, commit them and create a PR.

This is only one of the ways to work on this issue, you can do it another way if you prefer another approach.
I hope this helps.

**Comment by akumar1503** [comment]
It helped Thanks.
I have created a PR on [react-component](https://github.com/appirio-tech/react-components/pull/313) app. Please review.
