### ISSUE TITLE
Update TaaS Intake Form: Backend Calls - Goal Due Date: 12/5

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4130]
- Required Skills and Preferred Skills reference data needs updating to use EMSI standard.
- Once TaaS intake form is submitted, the "Bookings API" (name TBD) should be called and a record for each requested role, along with the associated skills, should be created.

### Tasks here (this list is managed by @maxceem)
- [x] create jobs on TaaS project creation
- [x] update skill dropdowns to list skills from Skills API
- [x] skills dropdowns should load all the pages from Skills API (and don't' make duplicate calls for each skills dropdown instance)
- [x] show TaaS Project link after project creation

**Comment by acshields** [comment]
@RishiRajSahu - This is the issue I gave you a heads up on a couple weeks ago, regarding some future updates that will be needed for the TaaS intake form. As you prepare for this feature, I would recommend chatting with Will Price and Nagendra (he will be owning TaaS App from the engineering standpoint) to learn more about the "Bookings API" they are currently planning, as well as any other questions you might have.

**Comment by wdprice** [comment]
The APIs are still in development, but I can at least outline the top level items.

- Skills selection list must populate with values pulled from api.topcoder.com/v5/skills. A skill provider id will need to specified - we will provide this at the time of implementation

- Create project as you do today on v5/projects, with a Type= TaaS. (I'm sure the actual field is different, we can hammer that out.

- POST the job, job description, number of openings, list of required skills, and other relevant values to to v5/jobs ([swagger here](https://github.com/topcoder-platform/taas-apis/blob/dev/docs/swagger.yaml))

- Update the the link on the button the appears on conclusion of intake to direct the user to TaaS-App (URL structure TBD)

**Comment by wdprice** [comment]
@RishiRajSahu @acshields - FYI, our TAAS APIs should be deployed to topcoder-dev tomorrow. Once deployed this ticket should be able to be worked on.

cc: @nkumar-topcoder

**Comment by nkumar-topcoder** [comment]
@RishiRajSahu  @acshields  Dev deployment of **taasapp** completed. 
The Dev integration For taasapp is completed. You can verify for JOB creation. Few pointers.

1. Endpoint : http://api.topcoder-dev.com/v5/taasapi/jobs
2. Swagger & Postman collection : https://github.com/topcoder-platform/taas-apis/tree/dev/docs
3. Roles: bookingmanager and u-bahn (pshah_manager user already has this.  for other user testing, that user needs to be part of v5/users). For job creation booking manager roles is mandatory.

cc: @wdprice

**Comment by RishiRajSahu** [comment]
Thanks @nkumar-topcoder for the info, will let you know about queries if arises

**Comment by RishiRajSahu** [comment]
@wdprice @nkumar-topcoder 
I been through the swagger as well as requirements mentioned by @acshields  and support provided by your backend apis - So these are the things required -
1. Updated skills api endpoint, currently we are using v3 it needs to be replaced with V5
2. The job object is mapping to each kind of resource option we provide in the form i.e. QA, Frontend, Backend etc. so a respective job(s) should be created for each type of resource when the project is created
3. On Project creation success page, provide the url to TaaS app for TaaS projects only

Now below are my updates for **each of above requirements**
**1.** Could you provide me the swagger for V5 skills ?
**2.** This would need the Connect backend api(which is projects api) to be updated so as and when the TaaS project creation is done we make call to TaaS backend also to create job(s), I personally not in favour of having any TaaS app/api logic reside on Connect Frontend/Backend side, it will unnecessarily create dependency/maintenance overhead. **What my suggestion is** to create a separate processor which listens to project's creation event(_like how salesforce is doing_) and take the event's payload and do all the processing required for TaaS app/api, maybe we can name that processor - TaaS-Processor, 
**Pros -** 

- All logic for TaaS resides in the processor, good scenario to exploit our event bus
- Deployment/change dependency removed  from Connect
- Extensible - in processor we can in future listen for other api's events also if required

**Cons-**
Effort to create new processor, which seems worth doable to me. I would be happy to take ownership of that if required as I am very well aware of what payload we send on the event and what your api's need as per swagger

**3.** Let us know the URL we can do it as and when required.

FYI @mtwomey @vikasrohit

**Comment by nkumar-topcoder** [comment]
@RishiRajSahu 

1) V5/User, v5/skills etc
—————
Swagger: https://github.com/topcoder-platform/u-bahn-api/blob/master/docs/swagger.yaml
Example:
http://api.topcoder-dev.com/v5/users?handle=<handle>
http://api.topcoder-dev.com/v5/skill-search/skills?organizationId=0d2320f9-be61-4ba4-973e-edc3bb682a69&keyword=selenium
2) Very well thought out analysis, can we have call with other stakeholder to discuss and finalize. 
@wdprice please share you thoughts, further we can take this offline.
3) This part is WIP, tentative :https://mfe.topcoder-dev.com/taas/myteams will confirm shortly.

**Comment by nkumar-topcoder** [comment]
@RishiRajSahu   
Regarding 2nd point for separate processor for Job creation, my view is
a) we are creating intake app for taas-app.
b) And, once intake form is complete -  posting taas end point
both are specific to taas requirement. Hence, only for posting to taas endpoint having a separate processor i believe is overhead in terms of publishing and consuming.

I understand your point on dependency but there is already intake app which is specific to project.
 your thoughts please

**Comment by RishiRajSahu** [comment]
@nkumar-topcoder If intake for TaaS is always going to be via new taas-app ? or Connect will also keep providing the option to create a TaaS intake ? If we are completely getting away from Connect for TaaS intakes then yes we don't need another processor and all the logic could reside in new taas-app.

**Comment by nkumar-topcoder** [comment]
@RishiRajSahu need to check from business view
cc : @wdprice

**Comment by nkumar-topcoder** [comment]
@RishiRajSahu 
Post discussion it has been decided to post for job from intake form.
thanks @vikasrohit @wdprice

**Comment by RishiRajSahu** [comment]
@nkumar-topcoder I think in this scenario it would be best to consume the event once the project is created, could you guys give heads-up on this so that I can launch the challenge for taas-processor ?

fyi @mtwomey

**Comment by RishiRajSahu** [comment]
@nkumar-topcoder regarding the below point
> Roles: bookingmanager and u-bahn (pshah_manager user already has this. for other user testing, that user needs to be part of v5/users). For job creation booking manager roles is mandatory.

currently in Connect any registered user can access TaaS intake form and create a project, but with conditions of roles, what is supposed to do for users with client role(just Topcoder User role), do we have to ignore the job creation for them ?

**Comment by maxceem** [comment]
I'd like to confirm how we match data we have in UI with API requests we send to TaaS API.
1. Should we put `resourceType` as a free text from Connect UI like **"Front End Developer"** or is there any predefined list of job types?
2. In UI we define the job `duration` but in API we have `startDate` and `endDate`. Should we save job with `startDate` as date of form submission, and `endDate = startDate + duration`?
3. In UI we have **Workload** field, but no place to save in API. So we ignore it, right?
4. In Job API we have `rate` field, but we don't have it in UI. So we always keep it as `hourly`, right?
5. In UI we have 2 fields for skills (required and optional). Should we put them all in one filed `skills` without marking as `required/optional`?

![image](https://user-images.githubusercontent.com/146016/100720020-15f74580-33c6-11eb-91e2-2fcd133feed3.png)

**Comment by nkumar-topcoder** [comment]
@maxceem 
1) ResourceType should be free text, currently there is no Job Type predefined.
2) Yes
3) Yes
4)Always keep Rate as weekly (https://github.com/topcoder-platform/taas-apis/blob/dev/docs/swagger.yaml)
5) Ideally yes.

For 2 and 5, i would reconfirm from business point of view @wdprice.

**Comment by RishiRajSahu** [comment]
@nkumar-topcoder so, should we ignore TaaS projects created by clients to be considered for job creation ?
and
where can we get the guid for Topcoder org ?

**Comment by RishiRajSahu** [comment]
@nkumar-topcoder could you please provide substitute of this https://api.topcoder-dev.com/v3/tags/?domain=SKILLS&status=APPROVED in v5/skills
basically we need all the skills we provide along with their category because that's how we are doing right now 

v3 skills data

```
{
            "id": 404,
            "name": "Zepto.js",
            "domain": "SKILLS",
            "status": "APPROVED",
            "categories": ["develop"],
            "priority": 0,
            "synonyms": null,
            "createdAt": "2016-05-18",
            "updatedAt": "2016-05-18",
            "createdBy": 1,
            "updatedBy": 1
        }
```

v5 skills data
```

{
      "created" : "2020-10-23T15:18:57.734Z",
      "uri" : null,
      "updatedBy" : null,
      "id" : "59ee7b42-f3f3-48c9-bdca-e8396b241793",
      "skillprovider" : {
         "createdBy" : "tc-Copilot",
         "id" : "7637ae1a-3b7c-44eb-a5ed-10ea02f1885d",
         "updatedBy" : null,
         "created" : "2020-05-05T11:02:49.718Z",
         "name" : "EMSI",
         "updated" : null
      },
      "updated" : null,
      "name" : "2D Computer Graphics",
      "externalId" : "KS1200Y77WTLF0Y9J7TM",
      "skillProviderId" : "7637ae1a-3b7c-44eb-a5ed-10ea02f1885d",
      "createdBy" : "TonyJ"
   }
```

also, skills endpoints needs to be accesible by every registered Topcoder user, as any Topcoder could fill up the TaaS intake.

**Comment by nkumar-topcoder** [comment]
@maxceem @RishiRajSahu 
Please note down the change for taas v5/Job creation. There has been change in req. now  all member can create Job creation (topcoder user role)Hence, earlier communication that only bookingmanager role should create a job is **not** valid.

The current dev  v5/job is still validates for bookingmanager role, i will inform once we apply the fix.

cc: @wdprice

**Comment by maxceem** [comment]
Thanks, @nkumar-topcoder.

Please, also have a look at the Rishi's comment above https://github.com/appirio-tech/connect-app/issues/4130#issuecomment-736400173.

Regular users cannot retrieve the list of skills from V5 `http://api.topcoder-dev.com/v5/skills` only admins can retrieve all the skills.

**Comment by nkumar-topcoder** [comment]
@maxceem @RishiRajSahu can you pls try with **u-bahn** role.

**Comment by maxceem** [comment]
Yes, @nkumar-topcoder users with "u-bahn" role can retrieve the skills list. Though at the moment TaaS Intake form is available for ALL users (link https://connect.topcoder-dev.com/new-project/talent-as-a-service).

So I'm no sure if there additional business requirements that we should hide this form for regular customer users, and only show it for special users with `u-bahn` role?

**Comment by maxceem** [comment]
@RishiRajSahu one more question here.
At the moment clients can add any arbitrary skills they want. 

![image](https://user-images.githubusercontent.com/146016/100838736-a774bf00-347b-11eb-9511-5ed4d4977ed4.png)

But Job API only allows the ids of the skills that are already in the DB. Should we disable the ability to add arbitrary skills? Or should we still allow entering any skills, but only send to Job API the skills that are already in DB? So the custom skills would be only saved in Connect App, but not in Job API.

**Comment by RishiRajSahu** [comment]
@maxceem As per me, let's allow arbitrary skills as well, and yes we will post only the DB skills to job API.

**Comment by nkumar-topcoder** [comment]
@RishiRajSahu Arbitrary skills are allowed but it won't be saved or posted any where right ?
The reason is we validate for valid skills while posting else job creation won't happen.
cc : @maxceem

**Comment by maxceem** [comment]
@nkumar-topcoder @RishiRajSahu

Regarding creating TaaS Jobs client-side. IMHO it has a few disadvantages:
- We would have to make several API requests per job which would slow down the project creation process for the customer user.
- But more importantly, there would be no guaranty that all jobs would be successfully created:
   - Some requests may fail because of user poor connection
   - User may leave the page without waiting for all the requests to be finished, so we may end up in the situation when the project is created, but all jobs or a part of the jobs are not created.

As creating a separate TaaS Processor may take time, we can consider putting the logic for creating TaaS Jobs into Project Service Kafka Consumer. Inside Projects API repo we have Kafka consumer https://github.com/topcoder-platform/tc-project-service/blob/develop/src/services/kafkaConsumer.js which already handles various things:

![image](https://user-images.githubusercontent.com/146016/100857753-be280f80-3495-11eb-8043-e1c26dc97c8e.png)

The disadvantage of putting the logic here is that this logic might be too specific and probably doesn't belong to the Project Service in general.
But the advantage is that it would be much more reliable. There would be much more chances that all requests for creating Jobs would be successfully for consistency. And we wouldn't force the customer user to send more data using his network.

@vikasrohit just would like to also confirm with you that you don't mind putting such logic there in case we decide to go with it.

**Comment by nkumar-topcoder** [comment]
@maxceem One of the downside of using processor (that was discussed earlier) is how to we track failure job posting. project and taas are different app, but At consumer side how do we know jobs created or not. 
cc @RishiRajSahu @vikasrohit

**Comment by maxceem** [comment]
@nkumar-topcoder yes, that's not a perfect solution. To check errors we would have to look into the `project-api-consumers` log on AWS.

But if we send requests client-side I guess the situation might be not much better.
Let's say customer sends a form for creating a new project with `10` jobs. The project has been successfully created and we are sending `10` job creation API requests. `9` requests were successful and `1` failed.
Should we show an error for the customer user in such a case? Even if show an error to the customer, the customer might ignore it and just close the window, so we would never know about it and we even wouldn't have logs for this error anywhere.

**Comment by maxceem** [comment]
Another wild idea @nkumar-topcoder @RishiRajSahu 

After creating jobs in Jobs API we can update the Project data and populate project details with ids of created jobs:

![image](https://user-images.githubusercontent.com/146016/100861134-13feb680-349a-11eb-86aa-4dafeb446ce7.png)

This way we can:
- Inside Connect App show some indicator if related Job was created or no
- We can add a button to manually create related jobs for records in Connect App if job was not initially created
- Potentially, we can update related job when we update project in Connect App (this would have a lot of decision to make, so not sure this would work)

**Comment by nkumar-topcoder** [comment]
@maxceem 

- regarding associating jobId with projectiD it's a good thought, but all stakeholder should agree on that.
- regarding using project consumer, This too was discussed and better to display error in frontend and display msg to reach out for support. That way user/customer is aware that Job creation has failed, but project creation might  have happened. Testing for all scenario is only way to mitigate here.
Checking error at AWS logs and tracking is bit difficult unless consumer adds a logic for failed jobs and alerting.

**Comment by maxceem** [comment]
@RishiRajSahu one more thing to confirm. 

As V5 skills don't have categories I guess we have to always show all the skills for all the job types. The only question, should we leave the logic for categories in place, if categories would be potentially added to the V5 skills?  Or should we remove the logic for the categories to not leave redundant code?

**Comment by RishiRajSahu** [comment]
@maxceem let's keep the categories logic in place with a comment-note.
So, we are all clear about the requirements now - 
1. Jobs api support creation via all user now
2. Skills api role relaxation is in progress, for time being we will share cred of dev user with booking-manager role, @nkumar-topcoder can provide that user

regarding adding jobId to project data as it would be another attribute to that json object, but would that be a patch request after the job is created ? Are you planning to show some alert icon on scope page in case any job creation failed ?

**Comment by nkumar-topcoder** [comment]
@RishiRajSahu @maxceem 

both v5/skills and v5/job posting now support topcoder member (topcoder user roles). Pls verify.

cc @wdprice

**Comment by nkumar-topcoder** [comment]
@RishiRajSahu @maxceem 

workload field is included at v5/job api. pls refer to the latest-swagger-doc. Details shared in slack

**Comment by maxceem** [comment]
### Task: skills dropdowns should load all the pages from Skills API (and don't' make duplicate calls for each skills dropdown instance)

1. Load all skills
   - We've updated the SkillsQuestion select to load skills from the Skills API V5 https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/SkillsQuestion/SkillsQuestionBase.jsx#L55
   - But Skills API only returns maximum 100 records per page.
   - So we have to retrieve all the pages one by one to get all the skills, something like this https://github.com/topcoder-platform/u-bahn-es-processor/blob/562ed642a7fb8094eb4d6eebc0a4bfab47f587c8/src/common/helper.js#L44-L49

2. At the moment we are showing several instances of the skills questions, and each of them is loading skills for itself:

    ![image](https://user-images.githubusercontent.com/146016/101486844-f16f1080-3965-11eb-864e-fff06022fda3.png)

    - As now we would have to load several pages, there would be even more requests.

    - So we have to load skills only once for all the instances.
    
    - There is some caching is implemented, but it doesn't work when we are showing all the components at the same time. So we have to fix it. The fix could be to create a function which would return a promise and that promise would return skills loaded or cached:
      ```js
      // so the idea of code can be like this

      function getSkills() {
         if (!getSkills.cachedPromise) {
            getSkills.cachedPromise = new Promise(resolve, reject) {
                // load all skills pages
                resolve(skills);
                // reject(error) if error
            }
         }

         return getSkills.cachedPromise;
      }

      // inside component 
      componentWillMount() {
          getSkills().then((skills) => { setOptions(....) }).catch(() => {...})
      }
      ```

**Comment by maxceem** [comment]
All is done as per this task description.

**Comment by drasticdpk** [comment]
Verified 
![image](https://user-images.githubusercontent.com/25297859/106157687-0f5d3280-61ab-11eb-9dc2-77c803766cfd.png)
![image](https://user-images.githubusercontent.com/25297859/106157845-39165980-61ab-11eb-8d7a-689b7f71eb8f.png)
