### ISSUE TITLE
Create Milestone

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#4410]
As a Connect Copilot/Manager/Admin I can add milestones to a project.  

The data captured is as follows:

Must have:

- [ ] - Milestone Name
- [ ] - Description
- [ ] - Start Date (possibly calculate this based on the earliest challenge start date in the milestone.
- [ ] - End Date
- [ ] - Status - Draft, Planned, In Progress, Completed, Cancelled.

Out of scope :
- [ ] - Copilot(s) - should be a picklist based on the project copilots and not required.

Nice to have:

- [ ] - Copilot Payment: field per copilot that represents the amount they will be paid at the completion of the milestone. User entered by Topcoder and not available to other roles.
- [ ] - Budget - total budget for the milestone.  This should be synced with sfdc.  (Possibly defer this sync to another build cycle). Include a representation of how much has actually been used. (i.e. 45% of $10,000)
- [ ] - Work Estimated - # of challenges/tasks that are planned for the milestone
- [ ] - Work Progress - # of challenges and tasks completed / # challenges and tasks planned
- [ ] - Milestone Health -  Red/Yellow/Green
- [ ]   - Logic TBD
- [ ] - Approval - option for the customer to approve a milestone. For phase 1, we’ll just set a flag to approved.  Later, we’ll use that data point to create some additional logic and automation.

**Prototype:**  https://marvelapp.com/prototype/660ha87/screen/80289302

**Comment by drasticdpk** [comment]
Note : Few findings are logged over here. https://github.com/appirio-tech/connect-app/issues/4422#issuecomment-885608108
