### ISSUE TITLE
New Milestone Concept

### ISSUE THREAD

**Issue by elkhawajah** [appirio-tech/connect-app#4422]
This ticket explains the scope of initial new milestone concept development:

## Overview

Topcoder is improving the UX for communicating project plan and progress with customer, instead of using external tools like smartsheet, Topcoder wants it to be all in connect. 

We are starting with adding Milestone concept, this is like saying we have "Design Phase", "Development Phase", "QA and Bug Bash Phase" defined in smart sheet in higher level, then in each phase, we define the challenges or tasks that we plan to run.

In current release we only focus on defining these Phases.

In this release we are renaming "Phase" in the project details page to "Milestone". This change won't touch how customer create projects, or PM approve them. The feature is enabled once the project is active.

## Actions/Guidelines

- [x] By default for a new project, the milestone table will be empty, with Add button to add new milestone.
- [x] PM or Copilot can add milestones.
- [x] A milestone should have a name, description, start/end date, status and a budget. 
- [x] Assigning copilots per milestone is out of scope
- [x] A PM/Copilot can add/edit/delete a milestone.
- [x] Customer can only view milestones.
- [ ] The feature developed without a mobile responsive design to follow, we tried to make it look good in responsive as much as possible.

QA will be limited to this page only.

**Comment by drasticdpk** [comment]
@elkhawajah , overall function is working as expected. But there is some observation. 
1. When there is only one milestone, at that time it is not accessible in customer view.  
**Project** : https://connect.topcoder-dev.com/projects/18116 

![image](https://user-images.githubusercontent.com/25297859/126780968-48e8865e-010f-4544-bca7-d00b2c032f8e.png)

2. Let's update content of message from PHASE > Milestone

![image](https://user-images.githubusercontent.com/25297859/126781387-9795caf9-cad1-41d8-a3f1-8d1d1c0b57e3.png)


3. Let's show dropdown instead of normal textbox

![image](https://user-images.githubusercontent.com/25297859/126781625-8332c4fa-d963-46cc-882d-eaecca9acc1f.png)

4. Let's remove Action column for Customer View

![image](https://user-images.githubusercontent.com/25297859/126782467-ef58d99c-28fe-4173-81e9-791e1ec36087.png)

**Comment by coderhacker** [comment]
@elkhawajah adding one more finding.  All fields are not proper aligned as per design
![image](https://user-images.githubusercontent.com/62358241/126793763-77c46673-3f49-481a-af11-f3ff62b1de71.png)

**Comment by elkhawajah** [comment]
@drasticdpk ready for QA, we did fixes

**Comment by drasticdpk** [comment]
Verified. 
1. There is some confusion will create new issue for this. 
2. Ok
3. ok
4. ok
5. ok
6. ok
7.  Design alignment  > ok.

**Comment by drasticdpk** [comment]
Verified on Prod env. 

**Reference** : 

![image](https://user-images.githubusercontent.com/25297859/126964495-4e1001b8-fb14-495a-b4a7-0fca3b31b561.png)
