### ISSUE TITLE
Milestone Management - Bulk update feature 

### ISSUE THREAD

**Issue by elkhawajah** [appirio-tech/connect-app#4447]
- [x] in connect admin/pm/copilot can do bulk update the copilots in selected milestones
- [x] the user can bulk push the milestones dates
- [x] the user can bulk delete milestones 

prototype
https://marvelapp.com/prototype/660ha87/screen/81132237

**Comment by drasticdpk** [comment]
Prod verified.
