### ISSUE TITLE
Feature picker fixes

### ISSUE THREAD

**Issue by vic-appirio** [appirio-tech/connect-app#505]
I'm combining all the related issues under a task list for convenience:
- [x] Add responsive layout and resizing of the feature preview image - #365 
- [x] Change the "x"-mark with a button that says "Save & close" - #247 
- [x] Disable user select on most of the interactive elements - #280

**Comment by vic-appirio** [comment]
Fixed by Didi & Vic
